name: noor
description: أذكار وأدعية من كتاب حصن المسلم
version: 2.5.0+25009

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animations: ^2.0.8
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_remote_config: ^4.2.6
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  intl: ^0.18.1
  path_provider: ^2.1.1
  provider: ^6.0.5
  reorderables: ^0.6.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/launcher_icon_android.png"
  image_path_ios: "assets/icons/launcher_icon_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/launcher_icon_android.png"

flutter:
  uses-material-design: true

  assets:
    # Original (not available in the public repo)
    - assets/
    - assets/images/
    - assets/images/ribbons/
    - assets/images/social-buttons/
    - assets/images/home-header/
    - assets/images/home-cards/light/
    - assets/images/home-cards/dark/
    - assets/images/backgrounds/
    - assets/images/fav-buttons/
    - assets/icons/
    - assets/icons/titles/
    - assets/icons/fav/
    - assets/icons/settings/
    - assets/icons/bottom-nav/

    # Data files
    - assets/json/

  fonts:
    - family: SST Arabic
      fonts:
        - asset: assets/fonts/SST-Arabic-Light.ttf
          weight: 200
        - asset: assets/fonts/SST-Arabic-Roman.ttf
          weight: 400
        - asset: assets/fonts/SST-Arabic-Medium.ttf
          weight: 700
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
    - family: Geeza
      fonts:
        - asset: assets/fonts/Geeza-Pro-Regular.ttf
    - family: Uthman
      fonts:
        - asset: assets/fonts/UthmanTN1.otf
          weight: 500
        - asset: assets/fonts/UthmanTN1B.otf
          weight: 700
    - family: NoorIcons
      fonts:
        - asset: assets/fonts/NoorIcons.ttf
    - family: NoorSettingsIcons
      fonts:
        - asset: assets/fonts/NoorSettingsIcons.ttf
