name: noor
description: أذكار وأدعية من كتاب حصن المسلم

version: 2.5.0+25000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  firebase_remote_config: ^2.0.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^9.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  get_it: ^7.1.3
  intl: ^0.17.0
  path_provider: ^2.0.6
  provider: ^5.0.0
  reorderables: ^0.4.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/launcher_icon_android.png"
  image_path_ios: "assets/icons/launcher_icon_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/launcher_icon_android.png"

flutter:
  uses-material-design: true

  assets:
    # Original (not available in the public repo)
    - assets/
    - assets/images/
    - assets/images/ribbons/
    - assets/images/social-buttons/
    - assets/images/home-header/
    - assets/images/home-cards/light/
    - assets/images/home-cards/dark/
    - assets/images/backgrounds/
    - assets/images/fav-buttons/
    - assets/icons/
    - assets/icons/titles/
    - assets/icons/fav/
    - assets/icons/settings/
    - assets/icons/bottom-nav/

    # Data files
    - assets/json/

  fonts:
    - family: SST Arabic
      fonts:
        - asset: assets/fonts/SST-Arabic-Light.ttf
          weight: 200
        - asset: assets/fonts/SST-Arabic-Roman.ttf
          weight: 400
        - asset: assets/fonts/SST-Arabic-Medium.ttf
          weight: 700
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
    - family: Geeza
      fonts:
        - asset: assets/fonts/Geeza-Pro-Regular.ttf
    - family: NoorIcons
      fonts:
        - asset: assets/fonts/NoorIcons.ttf
    - family: NoorSettingsIcons
      fonts:
        - asset: assets/fonts/NoorSettingsIcons.ttf
